list = [
    {
        "type": "sound",
        "group": "0",
        "freq": [174, 174 / 2, 174 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#880808",
        "lightshow": 1 / (174 / 100),
        "name": "174 Hz",
        "de": "Erdenergie (Schmerzlinderung)",
        "en": "Earth Energy (Pain Relief)",
        "es": "Energía de la tierra (alivio del dolor)",
        "fr": "Énergie terrestre (soulagement de la douleur)",
        "it": "Energia terrestre (sollievo dal dolore)",
        "hr": "Zemaljska energija (ublažavanje bolova)",
        "tags": "1 2 3",
        "img": "img/nature-gf527aac49_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [285, 285 / 2, 285 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#06183f",
        "lightshow": 1 / (285 / 100),
        "name": "285 Hz",
        "de": "Energetisierend, Wundheilung, Narbenheilung",
        "en": "Energizing, wound healing, scar healing",
        "es": "Energizante, cicatrizante de heridas, cicatrizante",
        "fr": "Énergisant, cicatrisant",
        "it": "Energizzante, cicatrizzante",
        "hr": "Energiziranje, zacjeljivanje rana, zacjeljivanje ožiljaka",
        "tags": "1 2 3",
        "img": "img/hand-g507065235_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [396, 396 / 2, 396 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#e33235",
        "lightshow": 1 / (396 / 100),
        "name": "396 Hz",
        "de": "Auflösung negativer Glaubenssätze und Ängste (Wurzelchakra) (AUM)",
        "en": "Dissolution of negative beliefs and fears (root chakra) (AUM)",
        "es": "Disolución de creencias negativas y miedos (chakra raíz) (AUM)",
        "fr": "Dissolution des croyances négatives et des peurs (chakra racine) (AUM)",
        "it": "Dissoluzione di credenze e paure negative (chakra della radice) (AUM)",
        "hr": "Razrješenje negativnih uvjerenja i strahova (korijenska čakra) (AUM)",
        "tags": "1 2 3",
        "img": "img/lotus-g4284cce54_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [417, 417 / 2, 417 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#f7b352",
        "lightshow": 1 / (417 / 100),
        "name": "417 Hz",
        "de": "Resonanz und Veränderung (Sakralchakra)",
        "en": "Resonance and Change (Sacral Chakra)",
        "es": "Resonancia y Cambio (Chakra Sacro)",
        "fr": "Résonance et changement (chakra sacré)",
        "it": "Risonanza e cambiamento (chakra sacrale)",
        "hr": "Rezonancija i promjena (sakralna čakra)",
        "tags": "1 2 3",
        "img": "img/dandelions-g3b04e8636_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [528, 528 / 2, 528 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#fede33",
        "lightshow": 1 / (528 / 100),
        "name": "528 Hz",
        "de": "Liebe, Transformation, Herzenergie, DNA-Reparatur (Solarplexus)",
        "en": "Love, Transformation, Heart Energy, DNA Repair (Solar Plexus)",
        "es": "Amor, Transformación, Energía del Corazón, Reparación del ADN (Plexo Solar)",
        "fr": "Amour, transformation, énergie cardiaque, réparation de l'ADN (plexus solaire)",
        "it": "Amore, trasformazione, energia del cuore, riparazione del DNA (plesso solare)",
        "hr": "Ljubav, transformacija, energija srca, popravak DNK (Solarni pleksus)",
        "tags": "1 2 3",
        "img": "img/infant-g57184ba03_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [639, 639 / 2, 639 / 4],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#5ab048",
        "lightshow": 1 / (639 / 2 / 100),
        "name": "639 Hz",
        "de": "Harmonische Beziehungen, Kommunikation (Herzchakra)",
        "en": "Harmonious relationships, communication (heart chakra)",
        "es": "Relaciones armoniosas, comunicación (chakra del corazón)",
        "fr": "Relations harmonieuses, communication (chakra du cœur)",
        "it": "Relazioni armoniose, comunicazione (chakra del cuore)",
        "hr": "Harmonični odnosi, komunikacija (srčana čakra)",
        "tags": "1 2 3",
        "img": "img/conversation-g36eb3ddfe_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [741, 741 / 2, 741 / 4],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#2ab2e4",
        "lightshow": 1 / (741 / 2 / 100),
        "name": "741 Hz",
        "de": "Intuition, Lösungen finden (Halschakra)",
        "en": "Intuition, finding solutions (throat chakra)",
        "es": "Intuición, búsqueda de soluciones (chakra de la garganta)",
        "fr": "Intuition, trouver des solutions (chakra de la gorge)",
        "it": "Intuizione, trovare soluzioni (chakra della gola)",
        "hr": "Intuicija, pronalaženje rješenja (grlena čakra)",
        "tags": "1 2 3",
        "img": "img/light-gc12a26841_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [852, 852 / 2, 852 / 4],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#6f6aaa",
        "lightshow": 1 / (852 / 2 / 100),
        "name": "852 Hz",
        "de": "Verbindung mit der Energie des Universellen (Drittes Auge)",
        "en": "Connecting with the Energy of the Universal (Third Eye)",
        "es": "Conectando con la Energía de lo Universal (Tercer Ojo)",
        "fr": "Connexion avec l'énergie de l'universel (troisième œil)",
        "it": "Connessione con l'Energia dell'Universale (Terzo Occhio)",
        "hr": "Povezivanje s energijom univerzalnog (Treće oko)",
        "tags": "1 2 3",
        "img": "img/woman-g4836b432a_640.jpg"
    },
    {
        "type": "sound",
        "group": "0",
        "freq": [963, 963 / 2, 963 / 4],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#8b4a8a",
        "lightshow": 1 / (963 / 2 / 100),
        "name": "963 Hz",
        "de": "Göttliche spirituelle Energie (Kronenchakra)",
        "en": "Divine Spiritual Energy (Crown Chakra)",
        "es": "Energía Espiritual Divina (Chakra de la Corona)",
        "fr": "Énergie spirituelle divine (chakra de la couronne)",
        "it": "Energia Spirituale Divina (Chakra della Corona)",
        "hr": "Božanska duhovna energija (krunska čakra)",
        "tags": "1 2 3",
        "img": "img/heaven-g7a51feb35_640.jpg"
    },
    {
        "type": "sound",
        "group": "1",
        "freq": [144, 144 / 2, 144 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#a8afc0",
        "lightshow": 1 / (144 / 100),
        "name": "144 Hz",
        "de": "Hilfe bei Kopfschmerzen",
        "en": "Help with headaches",
        "es": "Ayuda con dolores de cabeza",
        "fr": "Aide aux maux de tête",
        "it": "Aiuta con il mal di testa",
        "hr": "Pomoć kod glavobolje",
        "tags": "1 2 3",
        "img": "img/man-gd6adb4c93_640.jpg"
    },
    {
        "type": "sound",
        "group": "1",
        "freq": [664, 664 / 2, 664 / 4],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#b1e55b",
        "lightshow": 1 / (664 / 2 / 100),
        "name": "664 Hz",
        "de": "Mehr Wachheit und Vitalität",
        "en": "More alertness and vitality",
        "es": "Más alerta y vitalidad",
        "fr": "Plus de vigilance et de vitalité",
        "it": "Più vigilanza e vitalità",
        "hr": "Više budnosti i vitalnosti",
        "tags": "1 2 3",
        "img": "img/boarding-gbb481ed70_640.jpg"
    },
    {
        "type": "sound",
        "group": "1",
        "freq": [965, 965 / 2, 965 / 4],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#795be5",
        "lightshow": 1 / (965 / 2 / 100),
        "name": "965 Hz",
        "de": "Muskelentspannung",
        "en": "muscle relaxation",
        "es": "relajación muscular",
        "fr": "relaxation musculaire",
        "it": "rilassamento muscolare",
        "hr": "opuštanje mišića",
        "tags": "1 2 3",
        "img": "img/connective-tissue-ga6d7e598b_640.jpg"
    },
    {
        "type": "sound",
        "group": "1",
        "freq": [802, 802 / 2, 802 / 4],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#e9e9ec",
        "lightshow": 1 / (802 / 100),
        "name": "802 Hz",
        "de": "Behandlung von Schnupfen und Erkältungen",
        "en": "Treatment of colds",
        "es": "Tratamiento de resfriados",
        "fr": "Traitement du rhume",
        "it": "Trattamento di raffreddori",
        "hr": "Liječenje prehlade",
        "tags": "1 2 3",
        "img": "img/ginger-g0c1145b24_640.jpg"
    },
    {
        "type": "sound",
        "group": "1",
        "freq": [304, 304 / 2, 304 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#d78a5a",
        "lightshow": 1 / (304 / 100),
        "name": "304 Hz",
        "de": "Gut bei Kopfschmerzen, Sedierung, Schmerzlinderung, Blutdruck, Muskelkater",
        "en": "Good for headache, sedation, pain relief, blood pressure, sore muscles",
        "es": "Bueno para el dolor de cabeza, sedación, alivio del dolor, presión arterial, dolores musculares",
        "fr": "Bon pour les maux de tête, la sédation, le soulagement de la douleur, la tension artérielle, les muscles endoloris",
        "it": "Buono per mal di testa, sedazione, sollievo dal dolore, pressione sanguigna, dolori muscolari",
        "hr": "Dobar za glavobolju, umirenje, ublažavanje boli, krvni tlak, bolne mišiće",
        "tags": "1 2 3",
        "img": "img/yoga-gea58ede33_640.jpg"
    },
    {
        "type": "sound",
        "group": "1",
        "freq": [330, 330 / 2, 330 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#9f3195",
        "lightshow": 1 / (330 / 100),
        "name": "330 Hz",
        "de": "Allergie Vorbeugung und Behandlung",
        "en": "Allergy prevention and treatment",
        "es": "Prevención y tratamiento de alergias",
        "fr": "Prévention et traitement des allergies",
        "it": "Prevenzione e cura delle allergie",
        "hr": "Prevencija i liječenje alergija",
        "tags": "1 2 3",
        "img": "img/flower-g686369a58_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [40, 40 / 2, 40 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#512396",
        "lightshow": 1 / (40 * 2 / 100),
        "name": "40 Hz",
        "de": "Konzentration und Fokus",
        "en": "concentration and focus",
        "es": "concentración y enfoque",
        "fr": "concentration",
        "it": "concentrazione e attenzione",
        "hr": "koncentracija i fokus",
        "tags": "1 2 3",
        "img": "img/adult-ge16ab3c40_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [432, 432 / 2, 432 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#06183f",
        "lightshow": 1 / (432 / 100),
        "name": "432 Hz",
        "de": "Tiefe Entspannung und Verbundenheit",
        "en": "Deep relaxation and connection",
        "es": "Relajación profunda y conexión.",
        "fr": "Détente profonde et connexion",
        "it": "Rilassamento profondo e connessione",
        "hr": "Duboko opuštanje i povezanost",
        "tags": "1 2 3",
        "img": "img/fox-g273081c1e_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [8.3 * 32, 8.3 * 32 / 2, 8.3 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#334976",
        "lightshow": 1 / (8.3 * 32 / 100),
        "name": "8.3 Hz",
        "de": "Hellsehen, visuelle Objekte",
        "en": "Clairvoyance, visual objects",
        "es": "Clarividencia, objetos visuales",
        "fr": "Voyance, objets visuels",
        "it": "Chiaroveggenza, oggetti visivi",
        "hr": "Vidovitost, vizualni objekti",
        "tags": "1 2 3",
        "img": "img/whale-g9b2a1dedb_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [90, 90 / 2, 90 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#ada167",
        "lightshow": 1 / (90 * 2 / 100),
        "name": "90 Hz",
        "de": "Gute Gefühle, Sicherheit, Wohlbefinden, Ausgleich",
        "en": "Good feelings, security, well-being, balance",
        "es": "Buenos sentimientos, seguridad, bienestar, equilibrio",
        "fr": "Bonnes sensations, sécurité, bien-être, équilibre",
        "it": "Buone sensazioni, sicurezza, benessere, equilibrio",
        "hr": "Dobri osjećaji, sigurnost, blagostanje, ravnoteža",
        "tags": "1 2 3",
        "img": "img/silhouette-g31411df0b_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [108, 108 / 2, 108 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#542507",
        "lightshow": 1 / (108 / 100),
        "name": "108 Hz",
        "de": "Integrales Wissen",
        "en": "integral knowledge",
        "es": "conocimiento integral",
        "fr": "connaissance intégrale",
        "it": "conoscenza integrale",
        "hr": "integralno znanje",
        "tags": "1 2 3",
        "img": "img/books-g545e686c6_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [420.82, 420.82 / 2, 420.82 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#c3eeec",
        "lightshow": 1 / (420.82 / 100),
        "name": "420.82 Hz",
        "de": "Liebe, Einfühlungsvermögen, Kreativität, Weiblichkeit, Anima",
        "en": "Love, empathy, creativity, femininity, anima",
        "es": "Amor, empatía, creatividad, feminidad, anima",
        "fr": "Amour, empathie, créativité, féminité, anima",
        "it": "Amore, empatia, creatività, femminilità, anima",
        "hr": "Ljubav, empatija, kreativnost, ženstvenost, anima",
        "tags": "1 2 3",
        "img": "img/woman-gffb1fd51d_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [20.215 * 16, 20.215 * 16 / 2, 20.215 * 16 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#1ac5bd",
        "lightshow": 1 / (20.215 * 16 / 100),
        "name": "20.215 Hz",
        "de": "Höhenflüge und LSD-ähnliche Zustände",
        "en": "High flights and LSD-like states",
        "es": "Altos vuelos y estados similares al LSD",
        "fr": "Vols élevés et états de type LSD",
        "it": "Voli alti e stati simili all'LSD",
        "hr": "Visoki letovi i stanja slična LSD-u",
        "tags": "1 2 3",
        "img": "img/forest-g8888c2f62_640.jpg"
    },
    {
        "type": "sound",
        "group": "2",
        "freq": [4.5 * 32, 4.5 * 32 / 2, 4.5 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#b5e875",
        "lightshow": 1 / (4.5 * 32 / 100),
        "name": "4.5 Hz",
        "de": "Schamanische Zustände",
        "en": "shamanic states",
        "es": "estados chamanicos",
        "fr": "états chamaniques",
        "it": "stati sciamanici",
        "hr": "šamanska stanja",
        "tags": "1 2 3",
        "img": "img/tribal-g6fb1667ac_640.jpg"
    },

    {
        "type": "sound",
        "group": "3",
        "freq": [4.11 * 32, 4.11 * 32 / 2, 4.11 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#2f5cb9",
        "lightshow": 1 / (4.11 * 32 / 100),
        "name": "4.11 Hz",
        "de": "Nieren",
        "en": "kidneys",
        "es": "riñones",
        "fr": "reins",
        "it": "reni",
        "hr": "bubrega",
        "tags": "1 2 3",
        "img": "img/kidney-g824c2738d_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [4.6 * 32, 4.6 * 32 / 2, 4.6 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#764d33",
        "lightshow": 1 / (4.6 * 32 / 100),
        "name": "4.6 Hz",
        "de": "Milz und Blut (emotionaler Impuls)",
        "en": "Spleen and blood (emotional impulse)",
        "es": "Bazo y sangre (impulso emocional)",
        "fr": "Rate et sang (impulsion émotionnelle)",
        "it": "Milza e sangue (impulso emotivo)",
        "hr": "Slezena i krv (emocionalni impuls)",
        "tags": "1 2 3",
        "img": "img/planet-gd76ab1f98_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [5.14 * 32, 5.14 * 32 / 2, 5.14 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#e5a416",
        "lightshow": 1 / (5.14 * 32 / 100),
        "name": "5.14 Hz",
        "de": "Magen (emotionale Akzeptanz)",
        "en": "Stomach (emotional acceptance)",
        "es": "Estómago (aceptación emocional)",
        "fr": "Estomac (acceptation émotionnelle)",
        "it": "Stomaco (accettazione emotiva)",
        "hr": "Želudac (emocionalno prihvaćanje)",
        "tags": "1 2 3",
        "img": "img/stomach-gc91ce83a7_640.png"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [5.35 * 32, 5.35 * 32 / 2, 5.35 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#cb18e0",
        "lightshow": 1 / (5.35 * 32 / 100),
        "name": "5.35 Hz",
        "de": "Lunge (Sauerstoff, Wärme)",
        "en": "lungs (oxygen, heat)",
        "es": "pulmones (oxígeno, calor)",
        "fr": "poumons (oxygène, chaleur)",
        "it": "polmoni (ossigeno, calore)",
        "hr": "pluća (kisik, toplina)",
        "tags": "1 2 3",
        "img": "img/upper-body-g61a50f82f_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [6.15 * 32, 6.15 * 32 / 2, 6.15 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#5e55a9",
        "lightshow": 1 / (6.15 * 32 / 100),
        "name": "6.15 Hz",
        "de": "Herz (Liebe, Wärme)",
        "en": "heart (love, warmth)",
        "es": "corazón (amor, calidez)",
        "fr": "coeur (amour, chaleur)",
        "it": "cuore (amore, calore)",
        "hr": "srce (ljubav, toplina)",
        "tags": "1 2 3",
        "img": "img/care-gb1da9284c_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [6.88 * 32, 6.88 * 32 / 2, 6.88 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#962874",
        "lightshow": 1 / (6.88 * 32 / 100),
        "name": "6.88 Hz",
        "de": "Schlüsselbein (Vitalität, Ausgewogenheit, Stabilität)",
        "en": "Clavicle (vitality, balance, stability)",
        "es": "Clavícula (vitalidad, equilibrio, estabilidad)",
        "fr": "Clavicule (vitalité, équilibre, stabilité)",
        "it": "Clavicola (vitalità, equilibrio, stabilità)",
        "hr": "Ključna kost (vitalnost, ravnoteža, stabilnost)",
        "tags": "1 2 3",
        "img": "img/male-g907e9db8b_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [7.69 * 32, 7.69 * 32 / 2, 7.69 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#103f19",
        "lightshow": 1 / (7.69 * 32 / 100),
        "name": "7.69 Hz",
        "de": "Schultern (starke Arme, Ausdehnung, Unterricht)",
        "en": "Shoulders (strong arms, stretching, teaching)",
        "es": "Hombros (brazos fuertes, estiramientos, enseñanza)",
        "fr": "Epaules (bras forts, étirements, enseignement)",
        "it": "Spalle (braccia forti, stretching, insegnamento)",
        "hr": "Ramena (jake ruke, istezanje, podučavanje)",
        "tags": "1 2 3",
        "img": "img/arm-g636c9e0fa_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [8.22 * 32, 8.22 * 32 / 2, 8.22 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#31644f",
        "lightshow": 1 / (8.22 * 32 / 100),
        "name": "8.22 Hz",
        "de": "Mund (Sprache, Kreativität)",
        "en": "mouth (language, creativity)",
        "es": "boca (lenguaje, creatividad)",
        "fr": "bouche (langage, créativité)",
        "it": "bocca (linguaggio, creatività)",
        "hr": "usta (jezik, kreativnost)",
        "tags": "1 2 3",
        "img": "img/teeth-g1ca9189ed_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [9.19 * 32, 9.19 * 32 / 2, 9.19 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#5b1326",
        "lightshow": 1 / (9.19 * 32 / 100),
        "name": "9.19 Hz",
        "de": "Oberlippe (Emotionen, Konfliktlösung)",
        "en": "Upper lip (emotions, conflict resolution)",
        "es": "Labio superior (emociones, resolución de conflictos)",
        "fr": "Lèvre supérieure (émotions, résolution de conflits)",
        "it": "Labbro superiore (emozioni, risoluzione dei conflitti)",
        "hr": "Gornja usna (emocije, rješavanje sukoba)",
        "tags": "1 2 3",
        "img": "img/kiss-g4097dbd6e_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [9.4 * 32, 9.4 * 32 / 2, 9.4 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#ef964b",
        "lightshow": 1 / (9.4 * 32 / 100),
        "name": "9.4 Hz",
        "de": "Prostata",
        "en": "prostate",
        "es": "próstata",
        "fr": "prostate",
        "it": "prostata",
        "hr": "prostate",
        "tags": "1 2 3",
        "img": "img/testicles-g3c5f2b0e9_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [10.3 * 16, 10.3 * 16 / 2, 10.3 * 16 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#9f3195",
        "lightshow": 1 / (10.3 * 16 / 100),
        "name": "10.3 Hz",
        "de": "Nase (Atmung, Geschmackssinn)",
        "en": "nose (breathing, sense of taste)",
        "es": "nariz (respiración, sentido del gusto)",
        "fr": "nez (respiration, sens du goût)",
        "it": "naso (respirazione, senso del gusto)",
        "hr": "nos (disanje, osjet okusa)",
        "tags": "1 2 3",
        "img": "img/nose-g66bc60356_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [10.7 * 16, 10.7 * 16 / 2, 10.7 * 16 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#0ca631",
        "lightshow": 1 / (10.7 * 16 / 100),
        "name": "10.7 Hz",
        "de": "Ohren (Gehör, formale Konzepte)",
        "en": "ears (hearing, formal concepts)",
        "es": "oídos (oído, conceptos formales)",
        "fr": "oreilles (ouïe, concepts formels)",
        "it": "orecchie (udito, concetti formali)",
        "hr": "uši (sluh, formalni pojmovi)",
        "tags": "1 2 3",
        "img": "img/ear-ga3cfbb604_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [12.3 * 16, 12.3 * 16 / 2, 12.3 * 16 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#857f08",
        "lightshow": 1 / (12.3 * 16 / 100),
        "name": "12.3 Hz",
        "de": "Augen (Visualisierung)",
        "en": "eyes (visualization)",
        "es": "ojos (visualización)",
        "fr": "yeux (visualisation)",
        "it": "occhi (visualizzazione)",
        "hr": "oči (vizualizacija)",
        "tags": "1 2 3",
        "img": "img/eye-g92873dafd_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [13.8 * 16, 13.8 * 16 / 2, 13.8 * 16 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#89f333",
        "lightshow": 1 / (13.8 * 16 / 100),
        "name": "13.8 Hz",
        "de": "Frontallappen (siebter Sinn, endgültige Entscheidungen)",
        "en": "Frontal lobes (seventh sense, final decisions)",
        "es": "Lóbulos frontales (séptimo sentido, decisiones finales)",
        "fr": "Lobes frontaux (septième sens, décisions finales)",
        "it": "Lobi frontali (settimo senso, decisioni finali)",
        "hr": "Frontalni režnjevi (sedmo čulo, konačne odluke)",
        "tags": "1 2 3",
        "img": "img/brain-gdf54a8d74_640.jpg"
    },
    {
        "type": "sound",
        "group": "3",
        "freq": [295.8, 295.8 / 2, 295.8 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#05ec93",
        "lightshow": 1 / (295.8 / 100),
        "name": "295.8 Hz",
        "de": "Fettzellen",
        "en": "fat cells",
        "es": "células grasas",
        "fr": "cellules adipeuses",
        "it": "cellule adipose",
        "hr": "masne stanice",
        "tags": "1 2 3",
        "img": "img/slimming-gd616c88f2_640.jpg"
    },

    {
        "type": "sound",
        "group": "4",
        "freq": [7.83 * 32, 7.83 * 32 / 2, 7.83 * 32 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#334976",
        "lightshow": 1 / (7.83 * 32 / 100),
        "name": "7.83 Hz",
        "de": "Schumann-Frequenz",
        "en": "Schumann frequency",
        "es": "frecuencia Schumann",
        "fr": "Fréquence Schumann",
        "it": "Frequenza di Schumann",
        "hr": "Schumannova frekvencija",
        "tags": "1 2 3",
        "img": "img/planet-gd76ab1f98_640.jpg"
    },
    {
        "type": "sound",
        "group": "4",
        "freq": [126.22, 126.22 / 2, 126.22 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#a4954b",
        "lightshow": 1 / (126.22 / 100),
        "name": "126.22 Hz",
        "de": "Sonnen-Frequenz",
        "en": "solar frequency",
        "es": "frecuencia solar",
        "fr": "fréquence solaire",
        "it": "frequenza solare",
        "hr": "solarna frekvencija",
        "tags": "1 2 3",
        "img": "img/dandelion-g0d325b257_640.jpg"
    },
    {
        "type": "sound",
        "group": "4",
        "freq": [585.9375, 585.9375 / 2, 585.9375 * 2],
        "vol": [.8, .4, .3],
        "pan": [0, 0, 0],
        "col": "#e7d637",
        "lightshow": 1 / (585.9375 / 100),
        "name": "585.9375 Hz",
        "de": "Heil-Frequenz (150Mhz/256)",
        "en": "Heal Frequency (150Mhz/256)",
        "es": "Frecuencia de curación (150Mhz/256)",
        "fr": "Fréquence de guérison (150Mhz/256)",
        "it": "Frequenza di guarigione (150 Mhz/256)",
        "hr": "Frekvencija liječenja (150MHz/256)",
        "tags": "1 2 3",
        "img": "img/meadow-ga6a0d7d67_640.jpg"
    },
    {
        "type": "sound",
        "group": "4",
        "freq": [888, 444, 222],
        "vol": [.7, .4, .5],
        "pan": [0, 0, 0],
        "col": "#334976",
        "lightshow": 1 / (444 / 100),
        "name": "888 Hz",
        "de": "Manifestation",
        "en": "Manifestation",
        "es": "Manifestación",
        "fr": "Manifestation",
        "it": "Manifestazione",
        "hr": "Manifestacija",
        "tags": "1 2 3",
        "img": "img/be-gc787e4800_640.jpg"
    },

    {
        "type": "bin",
        "group": "5",
        "freq": [(7.83*11), (7.83*11) + 3],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#15961b",
        "lightshow": 1 / (3 / 100),
        "name": "3 Hz",
        "de": "Delta Spezial - Schumann + Delta 3",
        "en": "Delta Special - Schumann + Delta 3",
        "es": "Delta Special - Schumann + Delta 3",
        "fr": "Delta Special - Schumann + Delta 3",
        "it": "Delta Special - Schumann + Delta 3",
        "hr": "Delta Special - Schumann + Delta 3",
        "tags": "1 2 3",
        "img": "img/ai-generated-g94ce76027_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 3.5],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e09a4d",
        "lightshow": 1 / (35 / 100),
        "name": "3.5 Hz",
        "de": "Theta-Bereich - beschleunigte Speicherung der Sprache",
        "en": "Theta range - accelerated storage of speech",
        "es": "Rango theta: almacenamiento acelerado del habla",
        "fr": "Gamme Thêta - stockage accéléré de la parole",
        "it": "Gamma Theta: memorizzazione accelerata della parola",
        "hr": "Theta raspon - ubrzano pohranjivanje govora",
        "tags": "1 2 3",
        "img": "img/lion-g89034e545_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 5.5],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#333",
        "lightshow": 1 / (55 / 100),
        "name": "5.5 Hz",
        "de": "Visionen über notwendige Wachstumsprozesse",
        "en": "Visions of necessary growth processes",
        "es": "Visiones de procesos de crecimiento necesarios",
        "fr": "Visions des processus de croissance nécessaires",
        "it": "Visioni di processi di crescita necessari",
        "hr": "Vizije potrebnih procesa rasta",
        "tags": "1 2 3",
        "img": "img/filter-g5e7f24ab4_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 6.3],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e33235",
        "lightshow": 1 / (63 / 100),
        "name": "6.3 Hz",
        "de": "Beschleunigtes Lernen, verbesserte Gedächtnisleistung, mentale und astrale Projektionen",
        "en": "Accelerated learning, improved memory, mental and astral projections",
        "es": "Aprendizaje acelerado, memoria mejorada, proyecciones mentales y astrales.",
        "fr": "Apprentissage accéléré, mémoire améliorée, projections mentales et astrales",
        "it": "Apprendimento accelerato, memoria migliorata, proiezioni mentali e astrali",
        "hr": "Ubrzano učenje, poboljšano pamćenje, mentalne i astralne projekcije",
        "tags": "1 2 3",
        "img": "img/abacus-g4f6c2fe99_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 7],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#f7b352",
        "lightshow": 1 / (70 / 100),
        "name": "7 Hz",
        "de": "Beschleunigtes Lernen, verbesserte Gedächtnisleistung",
        "en": "Accelerated learning, improved memory performance",
        "es": "Aprendizaje acelerado, mejor rendimiento de la memoria",
        "fr": "Apprentissage accéléré, amélioration des performances de la mémoire",
        "it": "Apprendimento accelerato, prestazioni di memoria migliorate",
        "hr": "Ubrzano učenje, poboljšana izvedba pamćenja",
        "tags": "1 2 3",
        "img": "img/paper-g84892f294_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 7.5],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#fede33",
        "lightshow": 1 / (75 / 100),
        "name": "7.5 Hz",
        "de": "Geführte Meditationen, Kreativität in Kunst/Erfindungen/Musik, Kontakt zu geistigen Bewusstseinsformen",
        "en": "Guided meditations, creativity in art/inventions/music, exposure to spiritual forms of consciousness",
        "es": "Meditaciones guiadas, creatividad en arte/invenciones/música, exposición a formas espirituales de conciencia",
        "fr": "Méditations guidées, créativité dans l'art/inventions/musique, exposition à des formes spirituelles de conscience",
        "it": "Meditazioni guidate, creatività nell'arte/invenzioni/musica, esposizione a forme spirituali di coscienza",
        "hr": "Vođene meditacije, kreativnost u umjetnosti/izumima/glazbi, izlaganje duhovnim oblicima svijesti",
        "tags": "1 2 3",
        "img": "img/colorful-gf04857371_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 7.83],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#486cb0",
        "lightshow": 1 / (78 / 100),
        "name": "7.83 Hz",
        "de": "Elementare Schumann Resonanz",
        "en": "Elementary Schumann Resonance",
        "es": "Resonancia elemental de Schumann",
        "fr": "Résonance Schumann élémentaire",
        "it": "Risonanza di Schumann elementare",
        "hr": "Elementarna Schumannova rezonancija",
        "tags": "1 2 3",
        "img": "img/frequency-g5def81d85_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 8],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#2ab2e4",
        "lightshow": 1 / (80 / 100),
        "name": "8 Hz",
        "de": "Alpha-Bereich - Regression in frühere Lebensphasen",
        "en": "Alpha range - regression to earlier stages of life",
        "es": "Rango alfa: regresión a etapas anteriores de la vida",
        "fr": "Gamme alpha - régression aux stades antérieurs de la vie",
        "it": "Gamma alfa - regressione alle prime fasi della vita",
        "hr": "Alfa raspon - regresija u ranije faze života",
        "tags": "1 2 3",
        "img": "img/night-view-g7f6fe0e4e_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 8.3],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#6f6aaa",
        "lightshow": 1 / (83 / 100),
        "name": "8.3 Hz",
        "de": "Visualisierung mentaler Objekte",
        "en": "Visualization of mental objects",
        "es": "Visualización de objetos mentales.",
        "fr": "Visualisation des objets mentaux",
        "it": "Visualizzazione di oggetti mentali",
        "hr": "Vizualizacija mentalnih objekata",
        "tags": "1 2 3",
        "img": "img/maple-leaf-g038a1e4f1_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 9],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#8b4a8a",
        "lightshow": 1 / (90 / 100),
        "name": "9 Hz",
        "de": "Gewahrsein über die Ursachen körperlicher Unausgeglichenheiten",
        "en": "Awareness of the causes of physical imbalances",
        "es": "Conciencia de las causas de los desequilibrios físicos.",
        "fr": "Conscience des causes des déséquilibres physiques",
        "it": "Consapevolezza delle cause degli squilibri fisici",
        "hr": "Svijest o uzrocima tjelesne neravnoteže",
        "tags": "1 2 3",
        "img": "img/hands-gc41d68a32_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 10.5],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#334976",
        "lightshow": 1 / (105 / 100),
        "name": "10.5 Hz",
        "de": "Selbstheilung des Körpers",
        "en": "self-healing of the body",
        "es": "autocuración del cuerpo",
        "fr": "auto-guérison du corps",
        "it": "autoguarigione del corpo",
        "hr": "samoizlječenje tijela",
        "tags": "1 2 3",
        "img": "img/gemstone-g28de21b17_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 12],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#a4954b",
        "lightshow": 1 / (120 / 100),
        "name": "12 Hz",
        "de": "Zentrierung",
        "en": "centering",
        "es": "centrado",
        "fr": "centrage",
        "it": "centraggio",
        "hr": "centriranje",
        "tags": "1 2 3",
        "img": "img/harmony-g46ec50c30_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 33],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#512396",
        "lightshow": 1 / (33 / 100),
        "name": "33 Hz",
        "de": "Gamma-Bereich - Vibrationsgefühl, physische Aufgewühltheit",
        "en": "Gamma range - feeling of vibration, physical agitation",
        "es": "Rango gamma - sensación de vibración, agitación física",
        "fr": "Gamme Gamma - sensation de vibration, agitation physique",
        "it": "Gamma gamma - sensazione di vibrazione, agitazione fisica",
        "hr": "Gama raspon - osjećaj vibracije, fizička uznemirenost",
        "tags": "1 2 3",
        "img": "img/swirl-geda463af3_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 35],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#31549f",
        "lightshow": 1 / (35 / 100),
        "name": "35 Hz",
        "de": "Balance der Chakren",
        "en": "Balance of the chakras",
        "es": "Equilibrio de los chakras",
        "fr": "Équilibre des chakras",
        "it": "Equilibrio dei chakra",
        "hr": "Ravnoteža čakri",
        "tags": "1 2 3",
        "img": "img/droplet-gf9fbdcf52_640.jpg"
    },


    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 55],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e9e9ec",
        "lightshow": 1 / (55 / 100),
        "name": "55 Hz",
        "de": "Tantrischer Yoga, Stimulation der Kundalini-Kraft",
        "en": "Tantric Yoga, Stimulating the Kundalini Power",
        "es": "Yoga Tántrico, Estimulando el Poder Kundalini",
        "fr": "Yoga Tantrique, Stimulation du Pouvoir Kundalini",
        "it": "Tantra Yoga, Stimolare il Potere Kundalini",
        "hr": "Tantrička joga, stimulacija Kundalini moći",
        "tags": "1 2 3",
        "img": "img/saint-ga85fbbdfc_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 62],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#f8c67c",
        "lightshow": 1 / (62 / 100),
        "name": "62 Hz",
        "de": "Gefühl physischer Kraft",
        "en": "feeling of physical power",
        "es": "sensación de poder físico",
        "fr": "sensation de puissance physique",
        "it": "sensazione di forza fisica",
        "hr": "osjećaj fizičke moći",
        "tags": "1 2 3",
        "img": "img/man-g43f96aba3_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 63],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#a8afc0",
        "lightshow": 1 / (63 / 100),
        "name": "63 Hz",
        "de": "Astrale Projektionen",
        "en": "Astral Projections",
        "es": "Proyecciones Astrales",
        "fr": "Projections astrales",
        "it": "Proiezioni Astrali",
        "hr": "Astralne projekcije",
        "tags": "1 2 3",
        "img": "img/black-hole-g00cc7c7dd_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 70],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e3cc5e",
        "lightshow": 1 / (70 / 100),
        "name": "70 Hz",
        "de": "Mentale und astrale Projektionen",
        "en": "Mental and astral projections",
        "es": "Proyecciones mentales y astrales",
        "fr": "Projections mentales et astrales",
        "it": "Proiezioni mentali e astrali",
        "hr": "Mentalne i astralne projekcije",
        "tags": "1 2 3",
        "img": "img/lamp-ga434e4fc3_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 80],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#06183f",
        "lightshow": 1 / (80 / 100),
        "name": "80 Hz",
        "de": "Bindung von Raum und Zeit, Orientierung",
        "en": "Binding of space and time, orientation",
        "es": "Unión de espacio y tiempo, orientación.",
        "fr": "Liaison de l'espace et du temps, orientation",
        "it": "Legame di spazio e tempo, orientamento",
        "hr": "Vezivanje prostora i vremena, orijentacija",
        "tags": "1 2 3",
        "img": "img/compass-gb5b3731da_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 83],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#a4954b",
        "lightshow": 1 / (83 / 100),
        "name": "83 Hz",
        "de": "Öffnung des 3.Auges",
        "en": "Opening of the 3rd eye",
        "es": "Apertura del tercer ojo",
        "fr": "Ouverture du 3ème oeil",
        "it": "Apertura del 3° occhio",
        "hr": "Otvaranje 3. oka",
        "tags": "1 2 3",
        "img": "img/eye-gd05c61b68_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 90],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#adadad",
        "lightshow": 1 / (90 / 100),
        "name": "90 Hz",
        "de": "Wohlgefühl, Sicherheit, Ausgeglichenheit",
        "en": "Well-being, security, balance",
        "es": "Bienestar, seguridad, equilibrio",
        "fr": "Bien-être, sécurité, équilibre",
        "it": "Benessere, sicurezza, equilibrio",
        "hr": "Dobrobit, sigurnost, ravnoteža",
        "tags": "1 2 3",
        "img": "img/animal-g6e29370ee_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 105],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#b1e55b",
        "lightshow": 1 / (105 / 100),
        "name": "105 Hz",
        "de": "Überblick über komplexe Situationen",
        "en": "Overview of complex situations",
        "es": "Resumen de situaciones complejas",
        "fr": "Aperçu des situations complexes",
        "it": "Panoramica di situazioni complesse",
        "hr": "Pregled složenih situacija",
        "tags": "1 2 3",
        "img": "img/fractal-g2eed7d16c_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 108],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e38b53",
        "lightshow": 1 / (108 / 100),
        "name": "108 Hz",
        "de": "Totales Wissen",
        "en": "total knowledge",
        "es": "conocimiento total",
        "fr": "connaissance totale",
        "it": "conoscenza totale",
        "hr": "ukupno znanje",
        "tags": "1 2 3",
        "img": "img/books-g89d0d5e37_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 196],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#654b3b",
        "lightshow": 1 / (196 / 100),
        "name": "196 Hz",
        "de": "Gefühl grosser Beruhigung",
        "en": "Feeling of great calm",
        "es": "Sensación de gran calma",
        "fr": "Sensation de grand calme",
        "it": "Sensazione di grande calma",
        "hr": "Osjećaj velike smirenosti",
        "tags": "1 2 3",
        "img": "img/tealights-geb8741839_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 247],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e3d383",
        "lightshow": 1 / (247 / 100),
        "name": "247 Hz",
        "de": "Gefühl des Friedens",
        "en": "sense of peace",
        "es": "sensación de paz",
        "fr": "sentiment de paix",
        "it": "senso di pace",
        "hr": "osjećaj mira",
        "tags": "1 2 3",
        "img": "img/meadow-ga6a0d7d67_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 333],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#865e36",
        "lightshow": 1 / (333 / 100),
        "name": "333 Hz",
        "de": "Inspiration bis Ekstase",
        "en": "Inspiration to ecstasy",
        "es": "Inspiración al éxtasis",
        "fr": "Inspiration à l'extase",
        "it": "Ispirazione per l'estasi",
        "hr": "Inspiracija do ekstaze",
        "tags": "1 2 3",
        "img": "img/hiking-gd967dfc21_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 348],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#0c6410",
        "lightshow": 1 / (348 / 100),
        "name": "348 Hz",
        "de": "Gefühl der Liebe",
        "en": "feeling of love",
        "es": "sentimiento de amor",
        "fr": "sentiment d'amour",
        "it": "sentimento d'amore",
        "hr": "osjećaj ljubavi",
        "tags": "1 2 3",
        "img": "img/heart-g9a27ca01c_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 440],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e52f6e",
        "lightshow": 1 / (440 / 100),
        "name": "440 Hz",
        "de": "Verständnis",
        "en": "Understanding",
        "es": "Comprensión",
        "fr": "Compréhension",
        "it": "Comprensione",
        "hr": "Razumijevanje",
        "tags": "1 2 3",
        "img": "img/background-ge4989a578_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 494],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#a4954b",
        "lightshow": 1 / (494 / 100),
        "name": "494 Hz",
        "de": "Geistiges Erwachen",
        "en": "spiritual awakening",
        "es": "despertar espiritual",
        "fr": "Eveil spirituel",
        "it": "risveglio spirituale",
        "hr": "duhovno buđenje",
        "tags": "1 2 3",
        "img": "img/daisy-gae05a0139_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 698],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#e81414",
        "lightshow": 1 / (69 / 100),
        "name": "698 Hz",
        "de": "Starkes Liebesgefühl",
        "en": "Strong feeling of love",
        "es": "fuerte sentimiento de amor",
        "fr": "Fort sentiment d'amour",
        "it": "Forte sentimento d'amore",
        "hr": "Snažan osjećaj ljubavi",
        "tags": "1 2 3",
        "img": "img/happy-mothers-day-gbdb1f8275_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 794],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#334976",
        "lightshow": 1 / (79 / 100),
        "name": "794 Hz",
        "de": "Starker Wille",
        "en": "Strong will",
        "es": "Voluntad fuerte",
        "fr": "Forte volonté",
        "it": "Forte volontà",
        "hr": "Snažna volja",
        "tags": "1 2 3",
        "img": "img/pointing-gd2ad379fc_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 880],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#b1e55b",
        "lightshow": 1 / (88 / 100),
        "name": "880 Hz",
        "de": "Unbegrenzte Vorstellungskraft",
        "en": "Unlimited imagination",
        "es": "Imaginación ilimitada",
        "fr": "Imagination illimitée",
        "it": "Immaginazione illimitata",
        "hr": "Neograničena mašta",
        "tags": "1 2 3",
        "img": "img/wildlife-g82dff3606_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 988],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#829cce",
        "lightshow": 1 / (98 / 100),
        "name": "988 Hz",
        "de": "Vergeistigung",
        "en": "spiritualization",
        "es": "espiritualización",
        "fr": "spiritualisation",
        "it": "spiritualizzazione",
        "hr": "produhovljenje",
        "tags": "1 2 3",
        "img": "img/hands-gf96359ece_640.jpg"
    },
    {
        "type": "bin",
        "group": "5",
        "freq": [432, 432 + 1925],
        "vol": [1, 1],
        "pan": [1, -1],
        "col": "#1f9624",
        "lightshow": 1 / (192 / 100),
        "name": "1925 Hz",
        "de": "Gefühl der Erleuchtung, auch Euphorie",
        "en": "Feeling of enlightenment, also euphoria",
        "es": "Sensación de iluminación, también euforia.",
        "fr": "Sensation d'illumination, aussi d'euphorie",
        "it": "Sensazione di illuminazione, anche euforia",
        "hr": "Osjećaj prosvjetljenja, također i euforije",
        "tags": "1 2 3",
        "img": "img/woman-g0e390c31b_640.jpg"
    },

    {
        "type": "five",
        "group": "6",
        "freq": [174, 285, 396, 417, 528],
        "vol": [.6, .5, .4, .3, .2],
        "pan": [0, 0, 0, 0, 0],
        "col": "#334976",
        "lightshow": 1 / (174 / 100),
        "name": "174-528 Hz",
        "de": "Untere Körperhälfte",
        "en": "Lower half of the body",
        "es": "Mitad inferior del cuerpo",
        "fr": "Moitié inférieure du corps",
        "it": "Metà inferiore del corpo",
        "hr": "Donja polovica tijela",
        "tags": "1 2 3",
        "img": "img/men-g29e1ca941_640.jpg"
    },
    {
        "type": "five",
        "group": "6",
        "freq": [285, 396, 417, 528, 639],
        "vol": [.6, .5, .4, .3, .2],
        "pan": [0, 0, 0, 0, 0],
        "col": "#73f557",
        "lightshow": 1 / (285 / 100),
        "name": "285-639 Hz",
        "de": "Unten bis Mitte",
        "en": "bottom to middle",
        "es": "de abajo hacia el medio",
        "fr": "de bas en milieu",
        "it": "dal basso al centro",
        "hr": "odozdo prema sredini",
        "tags": "1 2 3",
        "img": "img/shoe-gad2c2199b_640.jpg"
    },
    {
        "type": "five",
        "group": "6",
        "freq": [396, 417, 528, 639, 741],
        "vol": [.6, .5, .4, .3, .2],
        "pan": [0, 0, 0, 0, 0],
        "col": "#a5dad8",
        "lightshow": 1 / (396 / 100),
        "name": "396-741Hz",
        "de": "Körpermitte",
        "en": "midsection",
        "es": "sección en medio",
        "fr": "abdomen",
        "it": "tronco",
        "hr": "središnji presjek",
        "tags": "1 2 3",
        "img": "img/belly-gf80e2a51b_640.jpg"
    },
    {
        "type": "five",
        "group": "6",
        "freq": [417, 528, 639, 741, 852],
        "vol": [.6, .5, .4, .3, .2],
        "pan": [0, 0, 0, 0, 0],
        "col": "#daa27f",
        "lightshow": 1 / (417 / 100),
        "name": "417-852Hz",
        "de": "Oben bis Mitte",
        "en": "top to middle",
        "es": "de arriba a medio",
        "fr": "du haut au milieu",
        "it": "dall'alto al centro",
        "hr": "vrh prema sredini",
        "tags": "1 2 3",
        "img": "img/woman-g7443a7634_640.jpg"
    },
    {
        "type": "five",
        "group": "6",
        "freq": [528, 639, 741, 852, 963],
        "vol": [.6, .5, .4, .3, .2],
        "pan": [0, 0, 0, 0, 0],
        "col": "#bd9eda",
        "lightshow": 1 / (528 / 100),
        "name": "528-963Hz",
        "de": "Obere Körperhälfte",
        "en": "Upper half of the body",
        "es": "Mitad superior del cuerpo",
        "fr": "Moitié supérieure du corps",
        "it": "Metà superiore del corpo",
        "hr": "Gornja polovica tijela",
        "tags": "1 2 3",
        "img": "img/woman-g904eb5e0b_640.jpg"
    },
    {
        "type": "five",
        "group": "6",
        "freq": [174, 396, 528, 741, 963],
        "vol": [.6, .5, .4, .3, .2],
        "pan": [0, 0, 0, 0, 0],
        "col": "#512396",
        "lightshow": 1 / (174 / 100),
        "name": "5/9",
        "de": "Jede zweite Frequenz",
        "en": "Every second frequency",
        "es": "Cada segunda frecuencia",
        "fr": "Chaque seconde fréquence",
        "it": "Ogni seconda frequenza",
        "hr": "Svaka druga frekvencija",
        "tags": "1 2 3",
        "img": "img/symbol-gd2ba77619_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [55, 110, 220, 400, 830],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#f33737",
        "lightshow": 1 / (110 / 100),
        "name": "110++",
        "de": "Hilft bei Sinusitis",
        "en": "Helps with sinusitis",
        "es": "Ayuda con la sinusitis",
        "fr": "Aide à la sinusite",
        "it": "Aiuta con la sinusite",
        "hr": "Pomaže kod upale sinusa",
        "tags": "1 2 3",
        "img": "img/burnout-gb6434d2d7_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [150, 160, 180, 550, 950],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#06183f",
        "lightshow": 1 / (160 / 100),
        "name": "160++",
        "de": "Hilft bei Migräne",
        "en": "Helps with migraines",
        "es": "Ayuda con las migrañas",
        "fr": "Aide aux migraines",
        "it": "Aiuta con l'emicrania",
        "hr": "Pomaže kod migrena",
        "tags": "1 2 3",
        "img": "img/woman-ge5959ecab_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [60, 70, 370, 830, 970],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#ada167",
        "lightshow": 1 / (70 / 100),
        "name": "70++",
        "de": "Hilft bei Schlaf-Apnoe",
        "en": "Helps with sleep apnea",
        "es": "Ayuda con la apnea del sueño.",
        "fr": "Aide à l'apnée du sommeil",
        "it": "Aiuta con l'apnea notturna",
        "hr": "Pomaže kod apneje za vrijeme spavanja",
        "tags": "1 2 3",
        "img": "img/male-gcc9d37102_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [60, 120, 190, 370, 490],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#daa27f",
        "lightshow": 1 / (120 / 100),
        "name": "120++",
        "de": "Hilft bei Hautproblemen",
        "en": "Helps with skin problems",
        "es": "Ayuda con los problemas de la piel.",
        "fr": "Aide aux problèmes de peau",
        "it": "Aiuta con i problemi della pelle",
        "hr": "Pomaže kod problema s kožom",
        "tags": "1 2 3",
        "img": "img/sunblock-g88c7fca6c_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [50, 78.125, 93.75, 370, 830],
        "vol": [.4, .4, .4, .5, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#a45d31",
        "lightshow": 1 / (370 / 100),
        "name": "50++",
        "de": "Hilft bei Akne",
        "en": "Helps with acne",
        "es": "Ayuda con el acné",
        "fr": "Aide contre l'acné",
        "it": "Aiuta con l'acne",
        "hr": "Pomaže kod akni",
        "tags": "1 2 3",
        "img": "img/acne-g9679220a6_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [80, 160, 350, 273.4375, 546.875],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#592606",
        "lightshow": 1 / (350 / 100),
        "name": "350++",
        "de": "Hilft bei Warzen",
        "en": "Helps with warts",
        "es": "Ayuda con las verrugas",
        "fr": "Aide avec les verrues",
        "it": "Aiuta con le verruche",
        "hr": "Pomaže kod bradavica",
        "tags": "1 2 3",
        "img": "img/skin-care-gf5cdb7556_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [110, 160, 240, 350, 570],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#f33737",
        "lightshow": 1 / (160 / 100),
        "name": "240++",
        "de": "Hilft bei Gelenkschmerzen",
        "en": "Helps with joint pain",
        "es": "Ayuda con el dolor en las articulaciones.",
        "fr": "Aide aux douleurs articulaires",
        "it": "Aiuta con dolori articolari",
        "hr": "Pomaže kod bolova u zglobovima",
        "tags": "1 2 3",
        "img": "img/body-gc12349c46_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [90, 260, 520, 650, 930],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#bd9eda",
        "lightshow": 1 / (260 / 100),
        "name": "260++",
        "de": "Schulter-, Arm- und Handbeschwerden",
        "en": "Shoulder, arm and hand ailments",
        "es": "Dolencias de hombro, brazo y mano",
        "fr": "Affections des épaules, des bras et des mains",
        "it": "Disturbi della spalla, del braccio e della mano",
        "hr": "Bolesti ramena, ruku i šaka",
        "tags": "1 2 3",
        "img": "img/back-ga0eefef51_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [80, 140, 147.85, 570, 730],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#334976",
        "lightshow": 1 / (140 / 100),
        "name": "140++",
        "de": "Lernen und Konzentration",
        "en": "Learning and concentration",
        "es": "Aprendizaje y concentracion",
        "fr": "Apprentissage et concentration",
        "it": "Apprendimento e concentrazione",
        "hr": "Učenje i koncentracija",
        "tags": "1 2 3",
        "img": "img/school-gec7aa12a9_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [12.3 * 4, 25 * 4, 126.22, 393, 787],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#6690e7",
        "lightshow": 1 / (126.22 / 100),
        "name": "100++",
        "de": "Sehvermögen und Visualisierung",
        "en": "Eyesight and Visualization",
        "es": "Vista y Visualización",
        "fr": "Vue et visualisation",
        "it": "Vista e visualizzazione",
        "hr": "Vid i vizualizacija",
        "tags": "1 2 3",
        "img": "img/eye-gc16197ec0_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [126.22, 130, 396, 400, 620],
        "vol": [.4, .5, .4, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#e7d266",
        "lightshow": 1 / (396 / 100),
        "name": "130++",
        "de": "Ruhiger Schlaf",
        "en": "Peaceful sleep",
        "es": "Sueño tranquilo",
        "fr": "Sommeil paisible",
        "it": "Sonno tranquillo",
        "hr": "Miran san",
        "tags": "1 2 3",
        "img": "img/cat-g904bb0086_640.jpg"
    },
    {
        "type": "five",
        "group": "2",
        "freq": [211.44 / 2, 211.44 * 2, 211.44, 333, 666],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#bfb2ec",
        "lightshow": 1 / (211.44 / 100),
        "name": "211++",
        "de": "Inspiration",
        "en": "Inspiration",
        "es": "Inspiración",
        "fr": "Inspiration",
        "it": "Ispirazione",
        "hr": "Inspiracija",
        "tags": "1 2 3",
        "img": "img/light-bulb-g946b1a600_640.jpg"
    },
    {
        "type": "five",
        "group": "10",
        "freq": [527.343 / 4, 527.343 / 2, 527.343, 528, 540],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#9eee54",
        "lightshow": 1 / (527.343 / 100),
        "name": "527.34",
        "de": "Dankbarkeit",
        "en": "Gratitude",
        "es": "Gratitud",
        "fr": "Gratitude",
        "it": "Gratitudine",
        "hr": "Zahvalnost",
        "tags": "1 2 3",
        "img": "img/man-g4448e1319_640.jpg"
    },
    {
        "type": "five",
        "group": "10",
        "freq": [488.28125 / 4, 488.28125 / 2, 488.28125, 488, 500],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#f33737",
        "lightshow": 1 / (488.28125 / 100),
        "name": "488.28",
        "de": "Liebe",
        "en": "Love",
        "es": "Amar",
        "fr": "Aimer",
        "it": "Amore",
        "hr": "Ljubav",
        "tags": "1 2 3",
        "img": "img/mountains-g7ab304a38_640.jpg"
    },
    {
        "type": "five",
        "group": "10",
        "freq": [390.625 / 4, 390.625 / 2, 390.625, 391, 400],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#795be5",
        "lightshow": 1 / (390.625 / 100),
        "name": "390.62",
        "de": "Verständnis",
        "en": "Understanding",
        "es": "Comprensión",
        "fr": "Compréhension",
        "it": "Comprensione",
        "hr": "Razumijevanje",
        "tags": "1 2 3",
        "img": "img/nature-gab3959806_640.jpg"
    },
    {
        "type": "five",
        "group": "10",
        "freq": [341.796875 / 4, 341.796875 / 2, 341.796875, 342, 350],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#e9e9ec",
        "lightshow": 1 / (341.796875 / 100),
        "name": "341.79",
        "de": "Versöhnung",
        "en": "Reconciliation",
        "es": "Reconciliación",
        "fr": "Réconciliation",
        "it": "Riconciliazione",
        "hr": "Pomirenje",
        "tags": "1 2 3",
        "img": "img/hd-wallpaper-g930180156_640.jpg"
    },
    {
        "type": "five",
        "group": "10",
        "freq": [302.734375 / 4, 302.734375 / 2, 302.734375, 303, 310],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#b1e55b",
        "lightshow": 1 / (302.734375 / 100),
        "name": "302.73",
        "de": "Zuversicht",
        "en": "Confidence",
        "es": "Confianza",
        "fr": "Confiance",
        "it": "Fiducia",
        "hr": "Samouvjerenost",
        "tags": "1 2 3",
        "img": "img/shoots-g779f87293_640.jpg"
    },
    {
        "type": "five",
        "group": "10",
        "freq": [244.140625 * 2, 244.140625 / 2, 244.140625, 244, 250],
        "vol": [.4, .4, .5, .4, .4],
        "pan": [0, 0, 0, 0, 0],
        "col": "#9f3195",
        "lightshow": 1 / (244.140625 / 100),
        "name": "244.14",
        "de": "Vertrauen",
        "en": "Trust",
        "es": "Relajación",
        "fr": "Relaxation",
        "it": "Rilassamento",
        "hr": "Opuštanje",
        "tags": "1 2 3",
        "img": "img/hands-g77a214e5e_640.jpg"
    },
];